server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
      routes:
        - id: servicio-lectura
          uri: lb://servicio-lectura
          predicates:
            - Path=/lectura/**
          filters:
            - AuthFilter
        - id: servicio-auth
          uri: lb://servicio-auth
          predicates:
            - Path=/auth/**
        - id: servicio-notificaciones
          uri: lb://servicio-notificaciones
          predicates:
            - Path=/notificaciones/**
          filters:
            - AuthFilter