server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: servicio-lectura
          uri: lb://servicio-lectura
          predicates:
            - Path=/lectura/**
          filters:
            - AuthFilter
        - id: servicio-auth
          uri: lb://servicio-auth
          predicates:
            - Path=/auth/**
        - id: servicio-notificaciones
          uri: lb://servicio-notificaciones
          predicates:
            - Path=/notificaciones/**
          filters:
            - AuthFilter