spring:
  application:
    name: servicio-notificaciones
  data:
    mongodb:
      host: localhost
      port: 27017
      database: NotificacionesBD
  mail:
    host: smtp-mail.outlook.com
    port: 587
    protocol: smtp
    username: joshivatapia@hotmail.com
    password: qgfiaigpmdqbvvjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
